#aplicação
spring.application.name=salas
#Conexão com o banco
spring.datasource.url=jdbc:h2:mem:salas
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
#Dialeto do h2 e criação automática das tabelas
spring.jpa.database-plataform=org.hibernate.dialect.H2Dialec
spring.jpa.hibernate.dll-auto=updade
#outros relacinados ao sql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#Banco no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2

